/*!

\mainpage mgfp: Mascot Generic Format (MGF) Parser
\author Marc Kirchner <marc.kirchner@childrens.harvard.edu>

\section sec_intro Introduction
\c mgfp is a flex/bison-based C++ MGF parser library.

\section sec_grammar The MGF Grammar
The following is the current MGF Grammar, as generated by Bison.
\verbinclude mgf_grammar.txt

\section sec_install Installation

\subsection sec_install_bin Obtaining a Binary Package

\subsection sec_install_src Building from Source

\section sec_examples Examples

*/

